# Generated by Django 5.2.17 on 2026-10-06 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
